<?php 
function first_block_theme($existing, $type, $theme, $path) {
  return [
    'banner-block' => [
      'variables' => [
        'header' => NULL,
        'subHeader' => NULL,
        'data'=> NULL,
      ],
    ],
    'about-block' => [
      'variables' => [
        'title' => NULL,
        'words' => NULL,
      ],
    ],
    'project-block' => [
      'variables' => [
        'projectItems' => NULL,
        'modalItems' => NULL,
      ],
    ],
    'contact-block' => [
      'variables' => [
        'email' => NULL,
        'address' => NULL,
        'phone' => NULL,
      ]
    ]
  ];
} 
 ?>